"""Add loser_id to MatchResult and Rating system

Revision ID: c67ac752ca2f
Revises: 88ce61f6a08c
Create Date: 2025-05-20 14:37:50.763238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67ac752ca2f'
down_revision: Union[str, None] = '88ce61f6a08c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_results', sa.Column('loser_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'match_results', 'users', ['loser_id'], ['id'])
    # ### end Alembic commands ###

    op.add_column(
        'users',
        sa.Column('rating', sa.Integer(), nullable=False, server_default='1500')
    )
    op.add_column(
        'users',
        sa.Column('games_played', sa.Integer(), nullable=False, server_default='0')
    )

    # 2) Now that the column exists and has no NULLs, drop the default
    op.alter_column('users', 'rating', server_default=None)
    op.alter_column('users', 'games_played', server_default=None)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'games_played')
    op.drop_column('users', 'rating')
    op.drop_constraint(None, 'match_results', type_='foreignkey')
    op.drop_column('match_results', 'loser_id')
    # ### end Alembic commands ###
