"""add elo change

Revision ID: cc9780a492ad
Revises: c67ac752ca2f
Create Date: 2025-05-22 23:14:09.443969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9780a492ad'
down_revision: Union[str, None] = 'c67ac752ca2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_results', sa.Column('winner_elo_change', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('match_results', sa.Column('loser_elo_change', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_results', 'loser_elo_change')
    op.drop_column('match_results', 'winner_elo_change')
    # ### end Alembic commands ###
